<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="iaca"
    nsURI="http://iaca/1.0" nsPrefix="iaca">
  <eClassifiers xsi:type="ecore:EClass" name="Attributs">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="t" eType="#//Type"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="EReference0" eType="#//Attributs"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//Type"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Component">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="att" upperBound="-1" eType="#//Attributs"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputs" lowerBound="1"
        upperBound="-1" eType="#//Input" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputs" lowerBound="1"
        upperBound="-1" eType="#//Output" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Library">
    <eStructuralFeatures xsi:type="ecore:EReference" name="c" lowerBound="1" upperBound="-1"
        eType="#//Component" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Bit" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Integer" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Long" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Real" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Char" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="String" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Input" abstract="true" eSuperTypes="#//IO"/>
  <eClassifiers xsi:type="ecore:EClass" name="Output" abstract="true" eSuperTypes="#//IO"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataInput" eSuperTypes="#//Input">
    <eStructuralFeatures xsi:type="ecore:EReference" name="connections" lowerBound="1"
        upperBound="-1" eType="#//DataConnection" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataOutput" eSuperTypes="#//Input #//Output"/>
  <eClassifiers xsi:type="ecore:EClass" name="EventInput" eSuperTypes="#//Input">
    <eStructuralFeatures xsi:type="ecore:EReference" name="connections" lowerBound="1"
        upperBound="-1" eType="#//EventConnection" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventOuput" eSuperTypes="#//Output"/>
  <eClassifiers xsi:type="ecore:EClass" name="IO" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//Type"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataConnection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="output" lowerBound="1"
        eType="#//DataOutput"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventConnection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="output" lowerBound="1"
        eType="#//EventOuput"/>
  </eClassifiers>
</ecore:EPackage>
